function options = calibrationOptions()
%CALIBRATIONOPTIONS Defaults for planar FIE calibration.

theta0 = [ ...
    1; 0.001; 1; ...
    0.001; 0.001; 1; ...
    0.001; 1; ...
    100000; 100000; ...
    0.001; 0.001; 1; ...
    0.001; 0.001; 1; ...
    0.8; ...
    0.001; 1; ...
    0.001; 1; ...
    0.001; 1; ...
    0];

lowerBound = 1e-4 * ones(24, 1);
upperBound = ones(24, 1);
lowerBound([2, 5, 12, 15]) = -1;
lowerBound(9:10) = 1e4;
upperBound(9:10) = 1e6;
lowerBound(24) = -0.05;
upperBound(24) = 0.05;

options = struct();
options.Theta0 = theta0;
options.LowerBound = lowerBound;
options.UpperBound = upperBound;

options.MaxIterations = 75;
options.StepWarmStart = 5;
options.FiniteDifferenceStep = 1e-8;
options.UseParallel = false;
options.SaveFirstNTrajectories = 5;

options.PsdEpsilon = 1e-5;
options.LmoSolver = 'mosek';
options.LmoVerbose = 0;

options.OutputDirectory = fullfile(pwd, 'outputs', 'matlab');
options.Estimator = struct( ...
    'CasadiSolver', 'ipopt', ...
    'IpoptPrintLevel', 0, ...
    'IpoptSilentBanner', 'yes', ...
    'PrintSolverTime', false, ...
    'CovarianceJitter', 1e-9, ...
    'FiniteDifferenceStep', options.FiniteDifferenceStep, ...
    'UseParallel', options.UseParallel);
end
